### ISSUE TITLE
Cake.exe : An error occurred when executing task 'Build-Solution'.

### ISSUE THREAD

**Issue by mklim-softserve** [Sitecore/Sitecore.HabitatHome.Platform#120]
**Describe the bug**
While runnign .\build.ps1 I get an error:
Cake.exe : An error occurred when executing task 'Build-Solution'.

**Screenshots**
![image](https://user-images.githubusercontent.com/45255984/49721874-95ccf800-fc63-11e8-884a-23f2d6cbb0ba.png)

**Comment by jeanfrancoislarente** [comment]
The error: "MSBuild: Could not locate executable"

Building outside of Visual Studio requires [MSBuild Tools for Visual Studio 2017](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017)

**Comment by mklim-softserve** [comment]
that helped, thx.
