### ISSUE TITLE
Sync-Unicorn Error

### ISSUE THREAD

**Issue by tanakamapondera** [Sitecore/Sitecore.HabitatHome.Platform#147]
**Describe the bug**
Habitat Home Deployment Failed at Sync-Unicorn

**To Reproduce**
Carryout all the same steps stated in the Getting Started Guide up till Local Build/Deployment, Installation.

**Expected behavior**
Deploy habitat home, if not run: .\build.ps1 -Target "Post-Deploy" & carry on. Error still appears and I do not know what is wrong. Is there an error with my files or am messing up somehow?
Please help :)

![unicorn](https://user-images.githubusercontent.com/43476830/53595188-9e4e1400-3b6a-11e9-8990-d4e0adb9a34f.JPG)

**Comment by jeanfrancoislarente** [comment]
Which branch are you using for this?
Do you have SXA installed and did you publish the newly installed site (after installing SXA) prior to deploying Habitat Home?

**Comment by tanakamapondera** [comment]
I'm using the master branch & honestly I forgot to install SXA first. (This is my second time installing Habitathome so it slipped my mind)

**Comment by jeanfrancoislarente** [comment]
No problem - let me know if you need additional help
