### ISSUE TITLE
Readme has not been updated for 9.2

### ISSUE THREAD

**Issue by davvves** [Sitecore/Sitecore.HabitatHome.Platform#165]
Codebase has been updated to 9.2 but readme still says to install Sitecore 9.1 and points to 9.1-compatible modules. Therefore it's unknown what modules are required to successfully install.

**Comment by jeanfrancoislarente** [comment]
Repo is open-source. Anyone can make updates to docs and submit a PR.

**Comment by jeanfrancoislarente** [comment]
Updated in release branch
