### ISSUE TITLE
An error occurred when executing task "Turn-On-Unicorn" of Habitat Home Commerce 9.2.0

### ISSUE THREAD

**Issue by viethoangpyco** [Sitecore/Sitecore.HabitatHome.Platform#174]
![hhc920_10](https://user-images.githubusercontent.com/6151021/70451369-d5792a80-1ad7-11ea-92b1-9c36e84a96fc.png)

My workaround is to add the following bold line to "Quick-Deploy" task in **build.cake** file:

Task("Quick-Deploy")
.IsDependentOn("Base-PreBuild")
.IsDependentOn("Base-Publish")
**.IsDependentOn("Apply-DotnetCore-Transforms");**

**Comment by jeanfrancoislarente** [comment]
Looks like a transform didn't get applied correctly in the first place. The default should be set to Off in the web.config.xdt

**Comment by jflheureux** [comment]
@viethoangpyco Which branch of the Platform and Commerce repositories did you use? At the time of writing these lines, correct branches are:

- Platform: master
- Commerce: master

**Comment by viethoangpyco** [comment]
@jflheureux FYI

- Platform: https://github.com/Sitecore/Sitecore.HabitatHome.Platform/releases/tag/9.2.0.0
- Commerce: master branch

**Comment by jflheureux** [comment]
So the error happened when executing `build.ps1` of the Platform or Commerce repository?

The way I install the commerce demo and its infrastructure is the following:

- Install Sitecore 9.2, SPE, and SXA using Sitecore.HabitatHome.Utilities
- Smart site publish
- Deploy the Platform demo using `.\build.ps1 -Target "Quick-Deploy"`
- Smart site publish
- Install Sitecore Commerce 9.2 and all of its modules using Sitecore.HabitatHome.Utilities
- Smart site publish
- Deploy the Commerce demo using `.\build.ps1 -Target "Initial"`
- Deploy the Commerce Engine demo using `.\deploy-commerce-engine.ps1 -Bootstrap -Initialize`
- Rebuild sitecore_master_index and sitecore_web_index

Is it the order you used as well?

**Comment by viethoangpyco** [comment]
@jflheureux no **Sitecore.HabitatHome.Utilities** in this case

Just based on https://github.com/Sitecore/Sitecore.HabitatHome.Commerce/blob/master/docs/installation.md

**Comment by jeanfrancoislarente** [comment]
What I used to do, and hope it helps / is still possible...

Install Sitecore 9.2 SPE, SXA using Utilities
Install Commerce 9.2 (using Utilities)
Smart Publish
Deploy Platform (Quick-Deploy)
Deploy Commerce (Initial)
Bootstrap
Publish
Rebuild Indexes.

Obviously the *most up-to-date* tried and tested are @jflheureux's steps.

**Comment by viethoangpyco** [comment]
@jeanfrancoislarente @jflheureux thanks for your suggestions. I just managed to install **Habitat Home Commerce 9.2** successfully without **HabitatHome.Utilities**

There are some other hiccups as well.

Regarding this issue, I add one more step to my install guide `execute .\build -Target “Apply-DotnetCore-Transforms”`

https://buoctrenmay.com/2019/12/10/sitecore-xc-9-2-0-demo-habitat-home-commerce-step-by-step-setup-guide/

**Comment by jflheureux** [comment]
For the moment, I am not able to reproduce the issue. I am keeping it open for other people to comment on their way to reproduce it, if any.

Thanks for reporting your issues @viethoangpyco.
