### ISSUE TITLE
Habitat Home page not opened.

### ISSUE THREAD

**Issue by Ameexramesh** [Sitecore/Sitecore.HabitatHome.Platform#178]
Hi ,

I have installed Sitecore 9.3 and i have to configured Habitat home with my instance i installed successfully. But Habitat home page not came and back end items are not created.

**Comment by jeanfrancoislarente** [comment]
Either publish the site or change the Site Grouping -> Habitat Home to use master database instead of web.

**Comment by PaulsonMac** [comment]
Thanks @jeanfrancoislarente , this worked fine for me

**Comment by jeanfrancoislarente** [comment]
Great, closing this as I haven't heard any other comments.
