### ISSUE TITLE
docker compose throws powershell error

### ISSUE THREAD

**Issue by rpatwaricdx** [Sitecore/Sitecore.HabitatHome.Platform#179]
I am trying to install HabitatHome in a docker. I have Installed 9.3 docker images according to 
https://github.com/Sitecore/docker-images

Steps to reproduce

1. Cloned Habitat, master
2. Run .\build.ps1 -DeploymentTarget DockerBuild
3. Run docker-compose build -m 16G --no-cache

Except the command

docker-compose -f docker-compose-vanilla.yml up -d

Any combination of docker-compose results in the error

![image](https://user-images.githubusercontent.com/46971007/79077987-36597f00-7cd3-11ea-9133-9403b2cbbc25.png)

**Comment by jeanfrancoislarente** [comment]
I'm working on fixing that early this week.

**Comment by sgisbert** [comment]
Hi! any update on this? I'm still getting the same error.

I downloaded all the mentioned packages in the docker-compose.yml file, but couldn't find where to copy them for this to work. I ended up commenting out the dockerfiles that made use of this to move on.

Would avoiding these files have any impact on the demo project? Any advice?

Thanks!

**Comment by jeanfrancoislarente** [comment]
I'm (finally) getting around to this again and noticed that the package it's looking for it Data Exchange Framework "scwdp.zip"

Please make sure you convert the Data Exchange Framework package downloaded from dev.sitecore.com into an scwdp using Sitecore Azure Toolkit. All of which can be found on dev.sitecore.com

I'm very sorry it took so long to address this.

**Comment by sgisbert** [comment]
Thanks!

and where should these packages be downloaded in order to be copied into the images? I couldn't get to the "install-module" folder

**Comment by jeanfrancoislarente** [comment]
You need to put the package into the `docker\images\windows\demo-xp-standalone` as well as `docker\images\windows\demo-xp-sqldev` folders.

There's a download-wdps.ps1 file which does it for our team (grabs from an azure fileshare and copies them to those two above folders)

The "install-module" folder is inside the container, not on your local system.

**Comment by sgisbert** [comment]
Yup, I did, but I guess it failed because the package was not .scwdp. Any chance to add a ENV variable to set a common location for packages? Assuming the same fix for the other packages also referenced in the docker-compose (Sitecore connect for SF, DAM, etc...)

Thanks!

**Comment by jeanfrancoislarente** [comment]
The issue will be the docker build context will still expect the files to be in the docker\images\... folder. You could modify the download-wdps script to accept a different download location but again, this assumes that it's already converted to an scwdp.

What's out there isn't ideal and makes a lot of assumptions. Our v10 approach is completely different and should be much easier. We're still a couple of weeks away from getting that ready though.

**Comment by sgisbert** [comment]
That's fine, thanks for your efforts. Glad to hear the demo will be upgraded to SC 10 soon. Keep us posted! :)

I will give it a try converting the packages to scwdp. Thanks!

**Comment by jeanfrancoislarente** [comment]
Great I'll close this now but please re-open if you have any more issues with this.
