### ISSUE TITLE
Habitat Home Site Page Returns System.InvalidOperationException

### ISSUE THREAD

**Issue by dionistakac88** [Sitecore/Sitecore.HabitatHome.Platform#181]
Hi, I completed all steps from guide without errors but after publishing Habitat Home site, I am getting exception on front page:

![Capture](https://user-images.githubusercontent.com/10938101/81047351-8b477a00-8eba-11ea-9b9e-311d5eab0f66.PNG)

**Comment by jeanfrancoislarente** [comment]
Curious, which branch were you using?

Remove Sitecore.Feature.Demo.Controller from the bin folder.

We've been in the middle of a lot of refactoring... Soon(ish) we'll be pushing out a mass amount of changes / stabilization. Let me know if you run into more issues please.

**Comment by dionistakac88** [comment]
I am on tags/930.0.0. 
Do you know which dll file contains Sitecore.Feature.Demo.Controller? Should I look on this path - C:\Projects\Sitecore.HabitatHome.Platform\src\Project\HabitatHome\code\bin ?

**Comment by jflheureux** [comment]
You seem to have deployed an older version of the demo (`Sitecore.Demo.[Layer]...`) on this Sitecore instance before deploying the latest one (`Sitecore.Demo.Shared.[Layer]...`).
Try going in the Sitecore instance bin folder and delete all `Sitecore.Demo.*.dll` files. Then redeploy using `.\build.ps1`

**Comment by dionistakac88** [comment]
I removed everything from Deploy folder where all files are deployed and I executed the command ".\build.ps1 -DeploymentTarget DockerBuild" in step 7 of this guide https://buoctrenmay.com/2019/12/23/sitecore-xp-9-3-0-and-sxa-9-3-0-demo-habitat-home-setup-guide/
Then I completed all other steps but I am still getting the same issue.

**Comment by adoprog** [comment]
Make sure the repo folders do not contain old untracked files, i.e. execute
`git clean -xdf`
then run ".\build.ps1 -DeploymentTarget DockerBuild"  again

**Comment by dionistakac88** [comment]
I managed to fix this by removing all dlls from bin folders and doing another build. It seems that I did first build on master branch, so I had redundant dlls which clashed with dlls generated from branch tags/930.0.0
