### ISSUE TITLE
Ability to deploy Habitat Home to a single or scaled Azure web deployment

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/Sitecore.HabitatHome.Platform#94]
Create the ability to build and deploy Habitat Home to Azure in a single or scaled configuration

**Comment by 26384sunilrana** [comment]
Hi Team, 
I got the below error.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.Pu
blishing.targets(3000,5): error : Copying file App_data\jobs\continuous\IndexWorker\App_data\Models\Sitecore.Demo.Platf
orm.Feature.CRM.CustomCollectionModels.CustomSalesforceConnectCollectionModel, 1.0.json to obj\Debug\Package\PackageTmp
\App_data\jobs\continuous\IndexWorker\App_data\Models\Sitecore.Demo.Platform.Feature.CRM.CustomCollectionModels.CustomS
alesforceConnectCollectionModel, 1.0.json failed. The specified path, file name, or both are too long. **The fully qualif
ied file name must be less than 260 characters, and the directory name must be less than 248 characters**. [C:\Sunil\Site
core\Projects\Habitat\Sitecore.Demo.Platform\src\Project\xConnect\code\Sitecore.Demo.Platform.XConnect.csproj]
An error occurred when executing task 'Publish-xConnect-Project'.
Error: One or more errors occurred.
        MSBuild: Process returned an error (exit code 1).

**Comment by jeanfrancoislarente** [comment]
As the error states your path is too long. 

We work in c:\projects and you’re in  [C:\Sunil\Site
core\Projects\Habitat\Sitecore.Demo.Platform... much longer. 

Please reduce the depth of the folder structure
